# Generated by Django 5.2 on 2025-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Home Décor', 'Home Décor'), ('Textiles', 'Textiles & Soft Furnishings'), ('Bedding', 'Bedding'), ('Kitchen', 'Kitchen & Dining'), ('Bathroom', 'Bathroom Accessories'), ('Storage', 'Storage & Organization'), ('Lighting', 'Lighting'), ('Outdoor', 'Outdoor Furnishings')], max_length=50)),
                ('embedded_image', models.TextField()),
            ],
        ),
    ]
